### ISSUE TITLE
Mod instructions are missing

### ISSUE THREAD

**Issue by matshou** [Jackiecrazy/Arms-of-the-Bowyer#1]
Without instructions on how to actually use the mod I am a bit lost. The original thread you provided on MinecraftForum doesn't mention it. For example, after watching a spotlight video of this mod I can see that the quiver can be placed on the back with the use of the _backspace_ key. Is this not working properly or is it mapped to a different key?

Anyway, we need to know which features are missing, which are broken, and which need to be implemented. A list in the wiki section would be nice.

**Comment by Jackiecrazy** [comment]
Quivers automatically load on your back when RenderPlayerAPI is installed. Currently we are missing:
3d arrow render. I think that's it.
What's broken:
quivers, arrow selection, bows slowing down the player, and a few others

**Comment by matshou** [comment]
How exactly do I install RenderPlayerAPI, since the instructions are missing I don't know what you are referring to and how to do it.

**Comment by Jackiecrazy** [comment]
There's an api. Assign as reference and add to api folder.

**Comment by Jackiecrazy** [comment]
Closing this then.
